export const USER_LOGGED_IN = 'USER_LOGGED_IN'
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT'
export const SET_EQPS = 'SET_EQPS'
export const GET_DATA = 'GET_DATA'
export const LOADING_USER = 'LOADING_USER'
export const USER_LOADED = 'USER_LOADED'
export const ADD_DEVICE = 'ADD_DEVICE'
